config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, except: [:destroy] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5).to_a }, numericality: { only_integer: true }
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
  has_many :reviews, dependent: :destroy
  CATEGORIES = %w[chinese italian japanese french belgian]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5).to_a }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show; end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f|%>
  <%= f.input :name %>
  <%= f.input :address, :as => :text %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORIES %>

  <div class="form-actions btn btn-dark rounded">
    <%= f.button :submit, :class => 'text-white' %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
  <div class="bg-white p-4 mt-3">
    <h2><%= link_to restaurant.name, restaurant_path(restaurant), class: "text-success"%></h2>
    <p>Address: <%= restaurant.address %></p>
    <p>Phone number: <%= restaurant.phone_number %></p>
    <p>Category: <%= restaurant.category %></p>
    <p>Reviews: <%= restaurant.reviews.count %></p>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h2 class="mb-4 text-success"><%= @restaurant.name %></h2>
<p>Address: <%= @restaurant.address %></p>
<p>Phone number: <%= @restaurant.phone_number %></p>
<p>Category: <%= @restaurant.category %></p>
<div class="d-flex justify-content-between align-items-end">
  <h4 class="mt-5">Reviews</h4>
  <%= link_to "Add Review", new_restaurant_review_path(@restaurant), class: "text-dark"  %>
</div>
<% @restaurant.reviews.each do |review| %>
  <div class="bg-white p-3 mt-2">
    <p><%= review.content %></p>
    <p><%= '⭐️' * review.rating %></p>
  </div>
<% end %>
<% if @restaurant.reviews.empty? %>
  <div class="bg-white p-3 mt-3">
    <p>No reviews available 🔎</p>
  </div>
<% end %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f|%>
  <%= f.input :content, :as => :text %>
  <%= f.input :rating, :as => :integer %>

   <div class="form-actions btn btn-dark rounded">
    <%= f.button :submit, :class => 'text-white' %>
  </div>
<% end %>